# This is a basic workflow to help you get started with Actions

name: GithubToBitbucket

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pushToBitbucket:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           cat ~/.ssh/id_rsa.pub
#          git remote add origin_bitbucket https://rakex:rhZEsfs4UheaXJaaJF4d@bitbucket.org/rakex/runtimelogger.git
#          git remote -v 
#          git checkout workflowtest
#          git show-branch
#          git push origin_bitbucket workflowtest
#          git push -u origin_bitbucket workflowtest
#          git remote add origin_bitbucket https://rakex@bitbucket.org/rakex/runtimelogger.git
#          git remote add origin_bitbucket https://rakex:rhZEsfs4UheaXJaaJF4d@bitbucket.org/rakex/runtimelogger.git
#          git push origin_bitbucket master
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          #config: ${{ secrets.CONFIG }} # ssh_config; optional
          #if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: Run a multi-line script
        run: |
          pwd
          ls /github/home/.ssh
          cat /github/home/.ssh/id_rsa.pub

